
server:
  port: 8088
mybatis:
  #实体类所做包
  type-aliases-package: com.micro.webpage.model
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰uName自动映射到u_name
spring:
  application:
    name: web-page
  servlet:
    multipart:
      location: D:\\micro
      max-file-size: 1MB
      max-request-size: 50MB
  datasource:
    username: root
    password:
    url: jdbc:mysql://www.test101.com:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                # 最大的连接数
      max-wait-millis: 60000                # 等待连接获取的最大超时时间
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
# freemarker:
#   charset: UTF-8
#   content-type: text/html
#  expose-request-attributes: true
#  expose-session-attributes: true
# expose-spring-macro-helpers: true
# suffix: .ftl
#  settings:
#  datetime_format: yyyy-MM-dd HH:mm:ss
#  default_encoding: UTF-8
#prefix:  classpath:/templates
  redis:
   database: 0
   #cluster:
   #  nodes:
   #   - 192.168.101.101:6379
   lettuce:
      pool:
          # 连接池中的最大空闲连接 默认8
        max-idle: 8
          # 连接池中的最小空闲连接 默认0
        min-idle: 0
          # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
   timeout: 30000
   host: 192.168.101.101
   port: 6379
   password:


